# Postgres configuration
spring.datasource.url = jdbc:postgresql://${DB_HOSTNAME:192.168.0.217}:5432/open_care
spring.datasource.username = ${POSTGRES_USERNAME:postgres}
spring.datasource.password = ${POSTGRES_PASSWORD:postgres}


spring.jpa.show-sql = true
spring.jpa.hibernate.ddl-auto =update

spring.liquibase.drop-first = false
spring.liquibase.default-schema = public
spring.liquibase.change-log=classpath:/db.changelog/db.changelog-master.yaml


##########################
# Swagger Configuration  #
##########################
springdoc.show-actuator=false
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs/public
springdoc.swagger-ui.display-request-duration=true
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.doc-expansion=no
springdoc.swagger-ui.defaultModelsExpandDepth=0
springdoc.swagger-ui.filter=true
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.disable-i18n=true

##########################
# Logging Configuration  #
##########################
logging.level.root=error
logging.level.sql=debug
logging.level.web=debug

###########################
# JWT Configuration       #
###########################
jwt-secret = ${JWT_SECRET:hffjhygbfjuribdbdgeyiienbdfbfkff}
jwt.token-expire-time = 10
jwt.refresh.token-expire-time = 10

###########################
# Email Configuration     #
###########################
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${INFO_MAIL:info.opencarebd@gmail.com}
spring.mail.password=${INFO_MAIL_PASSWORD:jqry yoxp nzoo qblp}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true



